timezone: Europe/Rome
permalink: pretty
repository: trasparente/rudra

# OPTIONS defaults
# class: site class
# language: en
# direction: ltr

# DEFAULTS
# values attached to pages
defaults:
  # Every page
  - scope:
      path: ''
    values:
      layout: default
      logo: true
      meta: true
      pagination: true
  # Docs
  - scope:
      path: ''
      type: docs
    values:
      sort_by: order
  # Posts
  - scope:
      path: ''
      type: posts
    values:
      sort_by: date

# COLLECTIONS
collections:
  posts:
    title: Blog
    permalink: /:categories/:title/
    # order: 1
  docs:
    title: Docs
    output: true
    # order: 3

# Forms
fields:
  hidden:
    value: text
    slug: text
  text:
    value: text
    title: text
    description: text
    autocomplete: text
    pattern: text
    minlength: number
    maxlength: number
    placeholder: text
    required: checkbox
    disabled: checkbox
  number:
    title: text
    description: text
    value: number
    min: number
    max: number
    step: number
    required: checkbox
    disabled: checkbox
  date:
    title: text
    description: text
    value: text
    required: checkbox
    disabled: checkbox
  select:
    title: text
    description: text
    value: text
    size: number
    required: checkbox
    multiple: checkbox
    disabled: checkbox
  checkbox:
    title: text
    description: text
    checked: checkbox
    required: checkbox
    disabled: checkbox
  radio:
    title: text
    description: text
    checked: checkbox
    required: checkbox
    disabled: checkbox